# 這個檔案告訴 Netlify 我們的伺服器功能在哪裡
[functions]
  directory = "netlify/functions/"

# --- v1.1.2 版新增 ---
# 新增重定向規則 (Redirect Rule)
# 這將解決 "Page not found" (404) 錯誤

[[redirects]]
  # 當使用者訪問根目錄 (首頁)
  from = "/"
  
  # 顯示這個檔案
  to = "/ai_tts_generator_v1.1.0.html"
  
  # 狀態 200 表示 "OK" (顯示內容)，而不是 301 (跳轉)
  status = 200

